server {
    server_name store.instaconnector.in;
    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/store.instaconnector.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/store.instaconnector.in/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

# ------------------------------------------------------------
# 2. STORE API 
# ------------------------------------------------------------
server {
    server_name store-api.instaconnector.in;
    location / {
        proxy_pass http://localhost:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/store.instaconnector.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/store.instaconnector.in/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

# ------------------------------------------------------------
server {
    listen 443 ssl;
    server_name *.instaconnector.in;
    ssl_certificate /etc/letsencrypt/live/instaconnector.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/instaconnector.in/privkey.pem;

    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        # Kubernetes NodePort
        proxy_pass http://localhost:32344;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header X-Forwarded-Proto https;
    }
}

# ------------------------------------------------------------
# 4. HTTP TO HTTPS REDIRECT
# ------------------------------------------------------------
server {
    listen 80;
    server_name *.instaconnector.in;
    return 301 https://$host$request_uri;
}