replicaCount: 1

image:
  repository: chetannn/medusa-backend
  tag: v2
  pullPolicy: Always

# Store ka unique naam (Node.js se pass hoga)
slug: "default-store" 
domain: "instaconnector.in"

store:
  type: "medusa"

service:
  type: ClusterIP

# Resources/Persistence same rahega...
resources:
  requests:
    cpu: 100m
    memory: 512Mi

persistence:
  enabled: true
  size: 1Gi

env:
  - name: DATABASE_TYPE
    value: "postgres"
  - name: NODE_ENV
    value: "development"
  - name: JWT_SECRET
    value: "supersecret"
  - name: COOKIE_SECRET
    value: "supersecret"

adminUser:
  email: "admin@default.com"
  password: "password123"

secrets:
  jwt: "supersecret"
  cookie: "supersecret"