apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    # 1. Backend API Port
    - name: backend
      port: 9000
      targetPort: 9000
      protocol: TCP
    
    # 2. Admin Panel Port
    - name: admin
      port: 7001
      targetPort: 7001
      protocol: TCP
  selector:
    app: {{ .Release.Name }}