replicaCount: 1

image:
  repository: wordpress
  pullPolicy: IfNotPresent
  tag: "latest"

store:
  type: "woocommerce"
  port: 80

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  host: "store.localhost" 


resources: 
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi