replicaCount: 1

image:
  repository: chetannn/custom-store-builder
  pullPolicy: IfNotPresent
  tag: "v1"

store:
  type: "woocommerce"
  port: 8080  

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  host: "store.localhost" 


wordpressUsername: "admin"
wordpressPassword: "password123"
wordpressEmail: "admin@example.com"

resources: 
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi